# ===========================
# Required settings
# ===========================

# Prefix of the input files.
# Pandora will look for files called <input>.* so make sure all files have the same prefix.
#dataset_prefix: /Users/julia/Desktop/Promotion/ADNA_Popgen/input/MathiesonEtAl_genotypes/full230.pruned
#dataset_prefix: /Users/julia/Desktop/Promotion/ADNA_Popgen/input/EuropeFullyPublic/west_eurasian_set/west_eurasian_set
dataset_prefix: /Users/julia/Desktop/Promotion/ADNA_Popgen/input/NearEastPublic/AncientLazaridis2016_ModernWestEurasia_final
#dataset_prefix: /Users/julia/Desktop/Promotion/ADNA_Popgen/input/NikosDaten/MySamples_PCA_project

# Name of the file format your dataset is in
# supported formats are:
# - ANCESTRYMAP
# - EIGENSTRAT
# - PED
# - PACKEDPED
# - PACKEDANCESTRYMAP
# default is EIGENSTRAT
file_format: PACKEDANCESTRYMAP

# Directory where to write the output to.
#result_dir: results/localtest/MathiesonEtAl_genotypes
result_dir: results/localtest/AncientLazaridis2016_ModernWestEurasia
#result_dir: results/localtest/NikosDaten

# ===========================
# Optional settings
# ===========================
# If set to True, do standard bootstrapping similarity analysis
# default is True
bootstrap: True

# Maximum number of bootstrap replicates to compute (default = TODO, currently 100).
n_bootstraps: 3

# If set to True, do a sliding window PCA along a whole genome and compare the similarity across the genome
# default is False
sliding_window: False

# TODO: sample projection of Ancient DNA samples
projected_populations: /Users/julia/Desktop/Promotion/ADNA_Popgen/input/NearEastPublic/modern.poplist.txt

# Number of threads to use for computation (default is number of cores).
threads: 2

# Seed for random number generator (default is current time).
seed: 0

# If set to True, reruns the analysis. Careful: this will overwrite existing results!
redo: False

# If set to True, plots the individual PCAs with the resulting K-Means clusters annotated.
plot_results: True

# PCs to plot, zero-indexed
plot_pcx: 0
plot_pcy: 1

# Number of Principal Components to output with smartPCA
# Comparing PCAs will be along all n_pcs Principal Components
# Default is 20 (same als smartPCA default)
n_pcs: 20

# Number of clusters to use for the K-Means clustering
# Only set this if you have prior knowledge about the correct number of clusters
# if not set, the optimal number k is determined automatically based on the BIC score and the number of
# populations and samples in your data
kmeans_k: 3

# TODO: write description
rogueness_cutoff: 0.95

# Optional path to the smartPCA executable. Per default, Pandora will use 'smartpca'.
# Specify a path if smartPCA is not installed system-wide on your machine.
smartpca: /Users/julia/micromamba/envs/pca_micromamba/bin/smartpca

# Optional path to the convertf executable. Per default, Pandora will use 'convertf'.
# Specify a path if convertf is not installed system-wide on your machine.
convertf: /Users/julia/micromamba/envs/pca_micromamba/bin/convertf


# Verbosity of the output logging of Pandora
# 0 = quiet, prints only errors and the results (loglevel = ERROR)
# 1 = verbose, prints all intermediate infos (loglevel = INFO)
# 2 = debug, prints intermediate infos and debug messages (loglevel = DEBUG)
verbosity: 2

# number of decimals to round the results to
# default is 2
result_decimals: 2

# smartPCA options
# in this section you can set any option that should be used for smartPCA
# for a list of possible settings see: https://github.com/DReichLab/EIG/blob/master/POPGEN/README
# not allowed are the following options: genotypename, snpname, indivname, evecoutname, evaloutname, numoutevec, maxpops
# use the following schema to set the options:
smartpca_optional_settings:
  shrinkmode: NO
  numoutlieriter: 0

