# ===========================
# Required settings
# ===========================

# Prefix of the input files.
# Pandora will look for files called <input>.* so make sure all files have the same prefix.
input: /Users/julia/Desktop/Promotion/ADNA_Popgen/input/MathiesonEtAl_genotypes/full230.pruned

# Directory where to write the output to.
output: results/localtest/MathiesonEtAl_genotypes

# ===========================
# Optional settings
# ===========================
# If set to True, do standard bootstrapping similarity analysis
# default is True
bootstrap: True

# Maximum number of bootstrap replicates to compute (default = TODO, currently 100).
bootstraps: 2

# If set to True, do a sliding window PCA along a whole genome and compare the similarity across the genome
# default is False
slidingWindow: False

# TODO: sample projection of Ancient DNA samples
projectSamples: False

# If set to True, determines bootstrap support values for each sample in the input data
# the support value is based on the similarity of PC vectors across bootstraps
# default is False
supportValues: False

# Number of threads to use for computation (default is number of cores).
threads: 2

# Seed for random number generator (default is current time).
seed: 0

# If set to True, reruns the analysis. Careful: this will overwrite existing results!
redo: False

# If set to True, plots the individual PCAs with the resulting K-Means clusters annotated.
plotResults: False

# PCs to plot, zero-indexed
plot_pcx: 0
plot_pcy: 1

# Cutoff to use when determining the number of PCs required.
# Pandora will automatically find the number of PCs required to explain at least
# <varianceCutoff>%% variance in the data. Default is 95%.
varianceCutoff: 0.95

# Number of clusters to use for the K-Means clustering
# Only set this if you have prior knowledge about the correct number of clusters
# if not set, the optimal number k is determined automatically based on the BIC score and the number of
# populations and samples in your data
kClusters: 3

# TODO: write description
roguenessCutoff: 0.95

# Optional path to the smartPCA executable. Per default, Pandora will use 'smartpca'.
# Specify a path if smartPCA is not installed system-wide on your machine.
smartpca: /Users/julia/micromamba/envs/pca_micromamba/bin/smartpca

# Optional path to the convertf executable. Per default, Pandora will use 'convertf'.
# Specify a path if convertf is not installed system-wide on your machine.
convertf: /Users/julia/micromamba/envs/pca_micromamba/bin/convertf


# Verbosity of the output logging of Pandora
# 0 = quiet, prints only errors and the results (loglevel = ERROR)
# 1 = verbose, prints all intermediate infos (loglevel = INFO)
# 2 = debug, prints intermediate infos and debug messages (loglevel = DEBUG)
verbosity: 2

# number of decimals to round the results to
# default is 2
resultsDecimals: 2

# smartPCA options
# in this section you can set any option that should be used for smartPCA
# for a list of possible settings see: https://github.com/DReichLab/EIG/blob/master/POPGEN/README
# not allowed are the following options: genotypename, snpname, indivname, evecoutname, evaloutname, numoutevec, maxpops
# use the following schema to set the options:
smartpcaOptionalSettings:
  shrinkmode: NO

