name: pandora
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pandas
  - numpy
  - scikit-learn >= 1.0
  - scipy
  - plotly
  - python-kaleido
  - pyyaml
  - pytest
  - pyarrow
  - eigensoft
  - scikit-allel
  - pip
  - pydantic >= 2
  - loguru
  - make
  - numpydoc
  - sphinx
  - sphinxcontrib-apidoc
  - sphinx_rtd_theme
